Traceback (most recent call last):
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 75, in <module>
    fail_test()
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 68, in fail_test
    x = 1 / 0
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 178, in <module>
    long_running_test()
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 133, in check_time
    raise TimeoutError
TimeoutError
Traceback (most recent call last):
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 188, in <module>
    long_running_test()
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 133, in check_time
    raise TimeoutError
TimeoutError
Traceback (most recent call last):
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 189, in <module>
    long_running_test()
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 170, in long_running_test
    print(i, "seconds have passed")
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 133, in check_time
    raise TimeoutError
TimeoutError
Traceback (most recent call last):
  File "code/Intro_Testing.py", line 273, in <module>
    print('The root of', x, 'is', my_sqrt(x))
  File "code/Intro_Testing.py", line 25, in my_sqrt
    while approx != guess:
  File "code/Intro_Testing.py", line 25, in my_sqrt
    while approx != guess:
  File "/Users/zeller/Projects/fuzzingbook/code/ExpectError.py", line 133, in check_time
    raise TimeoutError
TimeoutError
Traceback (most recent call last):
  File "code/Intro_Testing.py", line 309, in <module>
    exposed_sqrt("xyzzy")
  File "code/Intro_Testing.py", line 282, in exposed_sqrt
    x = int(s)
ValueError: invalid literal for int() with base 10: 'xyzzy'
Traceback (most recent call last):
  File "code/Intro_Testing.py", line 359, in <module>
    root = my_sqrt(0)
  File "code/Intro_Testing.py", line 27, in my_sqrt
    guess = (approx + x / approx) / 2
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "code/Intro_Testing.py", line 389, in <module>
    root = my_sqrt_fixed(-1)
  File "code/Intro_Testing.py", line 368, in my_sqrt_fixed
    assert 0 <= x
AssertionError
Test passed
Stopping total time:
0.0555804609975894
Stopping time in between:
4.673995135817677e-06
2.889699680963531e-05
3.124000068055466e-05
3.2921001547947526e-05
3.475500125205144e-05
3.664399991976097e-05
3.812799695879221e-05
3.9733997255098075e-05
4.137899668421596e-05
4.31059961556457e-05
0.0001849999971454963
0.034998292998352554
The root of 4 is 2.0
Start
0 seconds have passed
1 seconds have passed
2 seconds have passed
3 seconds have passed
Start
Start
Illegal Input
The root of 4 is 2.0
Illegal Number
Illegal Input
